# Generated by Django 2.2.1 on 2019-05-31 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='onsenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onsen_id', models.IntegerField()),
                ('onsen_name', models.CharField(max_length=20)),
                ('onsen_name_kana', models.CharField(max_length=30)),
                ('onsen_address', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=10)),
                ('prefecture', models.CharField(max_length=10)),
                ('large_area', models.CharField(max_length=10)),
                ('small_area', models.CharField(max_length=10)),
                ('nature_of_onsen', models.CharField(max_length=10)),
                ('onsen_area_name', models.CharField(blank=True, max_length=20, null=True)),
                ('onsen_area_name_kana', models.CharField(blank=True, max_length=30, null=True)),
                ('onsen_area_id', models.IntegerField(blank=True, null=True)),
                ('onsen_area_caption', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='onsenInnModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn_id', models.IntegerField()),
                ('inn_name', models.CharField(max_length=100)),
                ('inn_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('inn_min_price', models.IntegerField()),
                ('review_room', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('review_bath', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('review_breakfast', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('review_dinner', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('review_service', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('review_cleaness', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('number_of_rooms', models.IntegerField()),
                ('number_of_baths', models.IntegerField()),
                ('free_internet', models.BooleanField(blank=True, null=True)),
                ('convenience_store', models.BooleanField(blank=True, null=True)),
                ('hand_towel', models.BooleanField(blank=True, null=True)),
                ('tooth_brush_paste', models.BooleanField(blank=True, null=True)),
                ('bath_towel', models.BooleanField(blank=True, null=True)),
                ('shampoo', models.BooleanField(blank=True, null=True)),
                ('linse', models.BooleanField(blank=True, null=True)),
                ('body_soap', models.BooleanField(blank=True, null=True)),
                ('soap', models.BooleanField(blank=True, null=True)),
                ('yukata', models.BooleanField(blank=True, null=True)),
                ('pajama', models.BooleanField(blank=True, null=True)),
                ('bath_robe', models.BooleanField(blank=True, null=True)),
                ('drier', models.BooleanField(blank=True, null=True)),
                ('duvet', models.BooleanField(blank=True, null=True)),
                ('shaver', models.BooleanField(blank=True, null=True)),
                ('shower_cap', models.BooleanField(blank=True, null=True)),
                ('cotton_swab', models.BooleanField(blank=True, null=True)),
                ('onsui_toilet', models.BooleanField(blank=True, null=True)),
                ('hair_brush', models.BooleanField(blank=True, null=True)),
                ('onsen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onsen_inns.onsenModel')),
            ],
        ),
    ]
