# Generated by Django 2.2.1 on 2019-05-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsen_inns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onseninnmodel',
            old_name='bath_robe',
            new_name='bar_soap',
        ),
        migrations.RenameField(
            model_name='onseninnmodel',
            old_name='body_soap',
            new_name='bathrobe',
        ),
        migrations.RenameField(
            model_name='onseninnmodel',
            old_name='number_of_baths',
            new_name='baths_total',
        ),
        migrations.RenameField(
            model_name='onseninnmodel',
            old_name='drier',
            new_name='body_wash',
        ),
        migrations.RenameField(
            model_name='onseninnmodel',
            old_name='free_internet',
            new_name='conditioner',
        ),
        migrations.RenameField(
            model_name='onseninnmodel',
            old_name='linse',
            new_name='dental_amenities',
        ),
        migrations.RenameField(
            model_name='onseninnmodel',
            old_name='pajama',
            new_name='free_wifi',
        ),
        migrations.RenameField(
            model_name='onseninnmodel',
            old_name='shaver',
            new_name='hairdryer',
        ),
        migrations.RenameField(
            model_name='onseninnmodel',
            old_name='soap',
            new_name='pajamas',
        ),
        migrations.RenameField(
            model_name='onseninnmodel',
            old_name='tooth_brush_paste',
            new_name='razor',
        ),
        migrations.RenameField(
            model_name='onseninnmodel',
            old_name='number_of_rooms',
            new_name='rooms_total',
        ),
        migrations.AddField(
            model_name='onseninnmodel',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
