# Generated by Django 2.2.1 on 2019-05-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsen_inns', '0003_auto_20190531_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onseninn',
            name='baths_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onseninn',
            name='rooms_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
