# Generated by Django 2.2.1 on 2019-06-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsen_inns', '0004_auto_20190531_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsen',
            name='large_area',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='onsen',
            name='onsen_address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='onsen',
            name='onsen_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='onsen',
            name='onsen_name_kana',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='onsen',
            name='small_area',
            field=models.CharField(max_length=30),
        ),
    ]
