# Generated by Django 2.2.3 on 2019-07-05 01:07

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('onsen_inns', '0006_auto_20190601_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='onseninn',
            name='service_leisure',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=630, null=True, size=30),
        ),
        migrations.AlterField(
            model_name='onseninn',
            name='inn_photo',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
