# Generated by Django 2.2.3 on 2019-07-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsen_inns', '0008_auto_20190713_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onseninn',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='onseninn',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='onseninn',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
    ]
