# Generated by Django 2.2.3 on 2019-07-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsen_inns', '0009_auto_20190713_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onseninn',
            name='num_vote_down',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='onseninn',
            name='num_vote_up',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='onseninn',
            name='vote_score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
