# Generated by Django 2.2.3 on 2019-07-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsen_inns', '0011_auto_20190715_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='onseninn',
            name='inn_headline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onseninn',
            name='inn_overview',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='onseninn',
            name='inn_photo_2',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='onseninn',
            name='inn_photo_3',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='onseninn',
            name='inn_photo_4',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
