# Generated by Django 2.2.3 on 2019-07-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsen_inns', '0012_auto_20190718_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onseninn',
            name='inn_headline',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='onseninn',
            name='inn_overview',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
