# Generated by Django 2.2.3 on 2019-07-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsen_inns', '0013_auto_20190719_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onseninn',
            name='inn_overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
