# Generated by Django 2.2.1 on 2019-05-31 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onsen_inns', '0002_auto_20190531_0620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='onsenModel',
            new_name='Onsen',
        ),
        migrations.RenameModel(
            old_name='onsenInnModel',
            new_name='OnsenInn',
        ),
    ]
